In [1]:
# Clears all variable values previously set
# from IPython import get_ipython
# get_ipython().magic('reset -sf')

In [2]:
# Provides ways to work with large multidimensional arrays
import numpy as np 
# Allows for further data manipulation and analysis
import pandas as pd

# In Anaconda -> Environments -> Not Installed -> pandas-datareader -> Apply
from pandas_datareader import data as web # Reads stock data 
import matplotlib.pyplot as plt # Plotting
import matplotlib.dates as mdates # Styling dates
%matplotlib inline

import warnings
warnings.simplefilter("ignore")

## Constants

In [3]:
# Define path to files
# For MacOS
# PATH = "/Users/derekbanas/Documents/Tutorials/Python for Finance/"
# For Windows
PATH = "/Users/FranHome/Documents/data_science_main/ds_practicas/Python4Finance/"


In [4]:
# Make an Numpy array
list1 = [1,2,3,4,5,6]

npa1 = np.array(list1)
npa1


array([1, 2, 3, 4, 5, 6])

## Numpy Crash Course

NumPy is an amazing scientific computing library that is used by numerous other Python Data Science libraries. It contains many mathematical, array and string functions that are extremely useful. Along with all the basic math functions you'll also find them for Linear Algebra, Statistics, Simulation, etc.

NumPy utilizes vector (1D Arrays) and matrice arrays (2D Arrays).

## Create Array in Range

In [5]:
# Creates array from 0 to 4
npa2 = np.arange(0,11)
npa2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# Define a step
npa3 = np.arange(0,16,3)
npa3

array([ 0,  3,  6,  9, 12, 15])

## Matrices

In [7]:
# Create a 4 row matrix with 3 columns with all having a value of 1
mat1 = np.ones((4,3))
mat1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# Create a 4 row matrix with 3 columns with all having a value of 0
mat2 = np.zeros((4,3))
mat2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Random Matrices

In [9]:
# Random values between 0 and 50 as a matrix with 4 rows & 3 columns
mat3 = np.random.randint(0,50,(4,3))
mat3

array([[48, 48, 41],
       [41, 38,  9],
       [ 5, 31, 48],
       [19, 43, 31]])

## Generate Defined Number of Values in Range

In [10]:
# Generate 10 equally distanced values between 1 and 10
mat4 = np.linspace(1,10,10)
mat4

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Reshape Arrays

In [11]:
# Create array with 12 values
mat6 = np.random.randint(0,50,12)
mat6

array([ 8, 26, 31, 45, 12, 43, 22, 40, 49,  3, 11,  0])

In [12]:
# Reshape to a 3 row 4 column array
mat6 = mat6.reshape(3,4)
mat6

array([[ 8, 26, 31, 45],
       [12, 43, 22, 40],
       [49,  3, 11,  0]])

In [13]:
# Reshape into a 3D array with 3 blocks, 2 rows, 2 columns
mat7 = mat6.reshape(3,2,2)
mat7

array([[[ 8, 26],
        [31, 45]],

       [[12, 43],
        [22, 40]],

       [[49,  3],
        [11,  0]]])

In [14]:
# Reshape into a 3D array with 2 blocks, 3 rows, 2 columns
mat8 = mat6.reshape(2,3,2)
mat8

array([[[ 8, 26],
        [31, 45],
        [12, 43]],

       [[22, 40],
        [49,  3],
        [11,  0]]])

In [15]:
# Get the value in the 2nd block, 3rd row and 1st column
mat8[1,2,0]

np.int64(11)

## Filter Array

In [16]:
# Provide a boolean array where values are above 20
print(mat6)
mat6 > 20

[[ 8 26 31 45]
 [12 43 22 40]
 [49  3 11  0]]


array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [17]:
# Return an array with just values over 20
mat6[mat6 > 20]

array([26, 31, 45, 43, 22, 40, 49])

## Statistics Operations

In [18]:
# Generate 50 random values between 0 and 100
mat5 = np.random.randint(0,100,50)
mat5
print("Mean:", mat5.mean())
print("Standard Deviation:", mat5.std())
print("Variance:", mat5.var())
print("Min:", mat5.min())
print("Max:", mat5.max())

Mean: 50.1
Standard Deviation: 26.920809794655142
Variance: 724.7300000000001
Min: 0
Max: 99


## The Seed Function

In [19]:
# Used when you want to replicate randomization
np.random.seed(500)
mat9 = np.random.randint(0,50,10)
mat9

array([26,  1, 17, 14, 31,  8,  7, 13, 45, 17])

In [20]:
# Everything goes back to random on the next call
mat10 = np.random.randint(0,50,10)
mat10

array([17, 21, 41, 34, 42, 18, 19, 13, 38, 40])

# Pandas

Pandas provides numerous tools to work with tabular data like you'd find in spreadsheets or databases. It is widely used for data preparation, cleaning, and analysis. It can work with a wide variety of data and provides many visualization options. It is built on top of NumPy.

## Read Data from a CSV

In [21]:
def get_df_from_csv(ticker):
    try:
        df = pd.read_csv(PATH + ticker + '.csv', index_col='Date', 
                         parse_dates=True)
    except FileNotFoundError:
        pass
    else:
        return df

In [22]:
msft_df = get_df_from_csv("MSFT")
msft_df

,Adj Close,daily_return
Date,,
2017-01-03,58.291969,NaN
2017-01-04,58.031147,-0.004474
2017-01-05,58.031147,0.000000
2017-01-06,58.534157,0.008668
2017-01-09,58.347855,-0.003183
...,...,...
2021-08-31,301.880005,-0.005633
2021-09-01,301.829987,-0.000166
2021-09-02,301.149994,-0.002253


In [23]:
def get_df_from_csv2(ticker): 
    try:
        df = pd.read_csv(PATH + ticker + '.csv', index_col='Date',
                         parse_dates=True)
    except FileNotFoundError:
        pass
    else:
        return df

In [24]:
df_aapl = get_df_from_csv2('AAPL')
df_aapl

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-01-02,75.150002,73.797501,74.059998,75.087502,135480400.0,74.096443
2020-01-03,75.144997,74.125000,74.287498,74.357498,146322800.0,73.376083
2020-01-06,74.989998,73.187500,73.447502,74.949997,118387200.0,73.960770
2020-01-07,75.224998,74.370003,74.959999,74.597504,108872000.0,73.612930
2020-01-08,76.110001,74.290001,74.290001,75.797501,132079200.0,74.797081
...,...,...,...,...,...,...
2020-12-24,133.460007,131.100006,131.320007,131.970001,54930100.0,131.352829
2020-12-28,137.339996,133.509995,133.990005,136.690002,124486200.0,136.050766
2020-12-29,138.789993,134.339996,138.050003,134.869995,121047300.0,134.239273


## Read Data from Excel

In [25]:
def get_df_from_excel(file):
    try:
        df = pd.read_excel(file)
    except FileNotFoundError:
        pass
    else:
        return df

In [26]:
# You may have to run this in the Qt Console : pip install openpyxl
file = PATH + "stock_sectors.xlsx"
s_sectors = get_df_from_excel(file)
s_sectors

,Symbol,Name,Sector
0,MMM,3M,Industrials
1,AOS,A. O. Smith,Industrials
2,ABT,Abbott Laboratories,Health Care
3,ABBV,AbbVie,Health Care
4,ABMD,Abiomed,Health Care
...,...,...,...
500,YUM,Yum! Brands,Consumer Discretionary
501,ZBRA,Zebra Technologies,Information Technology
502,ZBH,Zimmer Biomet,Health Care
503,ZION,Zions Bancorp,Financials


In [27]:
def get_from_xls(file):
    try: 
        df = pd.read_excel(file)
    except FileNotFoundError:
        pass
    else: 
        return df

In [28]:
file = PATH + 'stock_sectors.xlsx'
stock_sec = get_from_xls(file)
stock_sec

,Symbol,Name,Sector
0,MMM,3M,Industrials
1,AOS,A. O. Smith,Industrials
2,ABT,Abbott Laboratories,Health Care
3,ABBV,AbbVie,Health Care
4,ABMD,Abiomed,Health Care
...,...,...,...
500,YUM,Yum! Brands,Consumer Discretionary
501,ZBRA,Zebra Technologies,Information Technology
502,ZBH,Zimmer Biomet,Health Care
503,ZION,Zions Bancorp,Financials


## Read Data from HTML

In [29]:
import requests

# 1. Define the Wikipedia URL
url = "https://en.wikipedia.org/wiki/List_of_current_United_States_governors"

# 2. Add a 'User-Agent' header to mimic a standard web browser
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# 3. Fetch the website content safely
response = requests.get(url, headers=headers)

# 4. Pass the text content into pandas (read_html returns a LIST of all tables)
tables = pd.read_html(response.text)
tables

[                                                    0
 0             This article is part of a series on the
 1              State governments of the United States
 2            State constitution Comparison Statehouse
 3                                           Executive
 4   State executives Governor (List) Other common ...
 5                                         Legislative
 6   State representatives (Alabama to Missouri, Mo...
 7                                           Judiciary
 8                     State supreme court State court
 9                                       Local offices
 10                                  District attorney
 11              Politics portal  United States portal
 12                                                vte,
                     State  Image            Governor[14]  Party[14]  \
 0          Alabama (list)    NaN                Kay Ivey        NaN   
 1           Alaska (list)    NaN           Mike Dunleavy        NaN   
 2          A

In [30]:
# We can define that we want the 2nd table on the page
df_govs_initial = tables[1]
df_govs_initial

,State,Image,Governor[14],Party[14],Party[14].1,Born,Prior public experience[15],Term start[14],Term end[14],Ref.
0,Alabama (list),NaN,Kay Ivey,NaN,Republican,"October 15, 1944 (age 81)",Lieutenant GovernorState Treasurer,"April 10, 2017",2027 (term limits),[17]
1,Alaska (list),NaN,Mike Dunleavy,NaN,Republican,"May 5, 1961 (age 65)",Alaska Senate,"December 3, 2018",2026 (term limits),[18]
2,Arizona (list),NaN,Katie Hobbs,NaN,Democratic,"December 28, 1969 (age 56)",Secretary of StateMinority Leader of the Arizo...,"January 2, 2023",2027,[19]
3,Arkansas (list),NaN,Sarah Huckabee Sanders,NaN,Republican,"August 13, 1982 (age 44)",White House Press Secretary,"January 10, 2023",2027,[20]
4,California (list),NaN,Gavin Newsom,NaN,Democratic,"October 10, 1967 (age 58)",Lieutenant GovernorMayor of San FranciscoSan F...,"January 7, 2019",2027 (term limits),[21]
5,Colorado (list),NaN,Jared Polis,NaN,Democratic,"May 12, 1975 (age 51)",U.S. HouseColorado State Board of Education,"January 8, 2019",2027 (term limits),[22]
6,Connecticut (list),NaN,Ned Lamont,NaN,Democratic,"January 3, 1954 (age 72)",Chair of the State Investment Advisory Council...,"January 9, 2019",2027,[23]
7,Delaware (list),NaN,Matt Meyer,NaN,Democratic,"September 29, 1971 (age 54)",Executive of New Castle County,"January 21, 2025",2029,[24]
8,Florida (list),NaN,Ron DeSantis,NaN,Republican,"September 14, 1978 (age 48)",U.S. House,"January 8, 2019",2027 (term limits),[25]
9,Georgia (list),NaN,Brian Kemp,NaN,Republican,"November 2, 1963 (age 62)",Secretary of StateGeorgia Senate,"January 14, 2019",2027 (term limits),[26]


In [31]:
# Create new df from initial df
df_govs_clean = df_govs_initial.copy()

In [32]:
# Remove brackets, make lowercase, replace spaces, remove edge spaces
df_govs_clean.columns = (
    df_govs_clean.columns
    .str.replace(r"\[.*\]", "", regex=True)
    .str.lower()
    .str.replace(" ", "")
    .str.strip()
)

df_govs_clean.head()


,state,image,governor,party,party.1,born,priorpublicexperience,termstart,termend,ref.
0,Alabama (list),NaN,Kay Ivey,NaN,Republican,"October 15, 1944 (age 81)",Lieutenant GovernorState Treasurer,"April 10, 2017",2027 (term limits),[17]
1,Alaska (list),NaN,Mike Dunleavy,NaN,Republican,"May 5, 1961 (age 65)",Alaska Senate,"December 3, 2018",2026 (term limits),[18]
2,Arizona (list),NaN,Katie Hobbs,NaN,Democratic,"December 28, 1969 (age 56)",Secretary of StateMinority Leader of the Arizo...,"January 2, 2023",2027,[19]
3,Arkansas (list),NaN,Sarah Huckabee Sanders,NaN,Republican,"August 13, 1982 (age 44)",White House Press Secretary,"January 10, 2023",2027,[20]
4,California (list),NaN,Gavin Newsom,NaN,Democratic,"October 10, 1967 (age 58)",Lieutenant GovernorMayor of San FranciscoSan F...,"January 7, 2019",2027 (term limits),[21]


In [33]:
# Remove columns
df_govs_clean.drop(columns=['image', 'party', 'ref.'], inplace=True)
df_govs_clean.head()

,state,governor,party.1,born,priorpublicexperience,termstart,termend
0,Alabama (list),Kay Ivey,Republican,"October 15, 1944 (age 81)",Lieutenant GovernorState Treasurer,"April 10, 2017",2027 (term limits)
1,Alaska (list),Mike Dunleavy,Republican,"May 5, 1961 (age 65)",Alaska Senate,"December 3, 2018",2026 (term limits)
2,Arizona (list),Katie Hobbs,Democratic,"December 28, 1969 (age 56)",Secretary of StateMinority Leader of the Arizo...,"January 2, 2023",2027
3,Arkansas (list),Sarah Huckabee Sanders,Republican,"August 13, 1982 (age 44)",White House Press Secretary,"January 10, 2023",2027
4,California (list),Gavin Newsom,Democratic,"October 10, 1967 (age 58)",Lieutenant GovernorMayor of San FranciscoSan F...,"January 7, 2019",2027 (term limits)


In [34]:
# Rename remaining column

df_govs_clean = df_govs_clean.rename(columns={'party.1':'party'})
df_govs_clean.head()

,state,governor,party,born,priorpublicexperience,termstart,termend
0,Alabama (list),Kay Ivey,Republican,"October 15, 1944 (age 81)",Lieutenant GovernorState Treasurer,"April 10, 2017",2027 (term limits)
1,Alaska (list),Mike Dunleavy,Republican,"May 5, 1961 (age 65)",Alaska Senate,"December 3, 2018",2026 (term limits)
2,Arizona (list),Katie Hobbs,Democratic,"December 28, 1969 (age 56)",Secretary of StateMinority Leader of the Arizo...,"January 2, 2023",2027
3,Arkansas (list),Sarah Huckabee Sanders,Republican,"August 13, 1982 (age 44)",White House Press Secretary,"January 10, 2023",2027
4,California (list),Gavin Newsom,Democratic,"October 10, 1967 (age 58)",Lieutenant GovernorMayor of San FranciscoSan F...,"January 7, 2019",2027 (term limits)


In [35]:
# Remove special characters from the state column
df_govs_clean.state = df_govs_clean.state.str.replace(r"\(.*\)","", regex=True)
df_govs_clean.head()

,state,governor,party,born,priorpublicexperience,termstart,termend
0,Alabama,Kay Ivey,Republican,"October 15, 1944 (age 81)",Lieutenant GovernorState Treasurer,"April 10, 2017",2027 (term limits)
1,Alaska,Mike Dunleavy,Republican,"May 5, 1961 (age 65)",Alaska Senate,"December 3, 2018",2026 (term limits)
2,Arizona,Katie Hobbs,Democratic,"December 28, 1969 (age 56)",Secretary of StateMinority Leader of the Arizo...,"January 2, 2023",2027
3,Arkansas,Sarah Huckabee Sanders,Republican,"August 13, 1982 (age 44)",White House Press Secretary,"January 10, 2023",2027
4,California,Gavin Newsom,Democratic,"October 10, 1967 (age 58)",Lieutenant GovernorMayor of San FranciscoSan F...,"January 7, 2019",2027 (term limits)


## US Demographics

In [ ]:
# You can also search for phrases in the table

url = "https://en.wikipedia.org/wiki/Demographics_of_the_United_States"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

response_demog = requests.get(url, headers=headers)

df_demog = pd.read_html(response_demog.text, match="Average population")[0]

# 2. Fix the doubled column names
# Option A: If you just want the second, more descriptive name (e.g., "birth" instead of "Crude rate / birth"):
df_demog.columns = [col[1] if "Unnamed" not in col[0] else col[1] for col in df_demog.columns]

# 3. View your clean table
df_demog.head()

## Replace Spaces in Column Names

In [ ]:
df_demog.columns = [x.replace(' ', '_') for x in df_demog.columns]
df_demog

## Remove Characters in Columns

In [ ]:
# Remove parentheses and whats inside them
df_demog.columns = df_demog.columns.str.replace(r"\(.*\)", "")
df_demog

df_demog.columns = df_demog.columns.str.replace(r"\[.*\]", "")
df_demog

## Rename Columns

In [ ]:
# You could add additional with commas between {}
df_demog = df_demog.rename(columns={'Total_fertility_rate[a]' : 
                                    'total_fertility_rate', 
                                    'Life_expectancy_(total)' : 'life_expectancy_total'})
df_demog.columns = df_demog.columns.str.lower()
df_demog

## Remove Characters in Columns

In [ ]:
# Removes brackets and what is inside for whole column
df_demog.year = df_demog.year.str.replace(r"\[.*\]", "",regex=True)
df_demog

In [ ]:
df_demog.info()

In [ ]:
df_demog = df_demog.drop(df_demog.index[-1])
df_demog.tail()

## Select Columns

In [ ]:
df_demog['live_births']

## Make a Column an Index

In [ ]:
df_demog.set_index('year', inplace=True)
df_demog

## Grab Data from Multiple Columns

In [ ]:
df_demog[['live_births', 'deaths']]

In [ ]:
df_demog[['deaths']].describe()

## Grab a Row

In [ ]:
df_demog.loc['2024']

In [ ]:
df_demog.iloc[234]

## Add a Column

In [ ]:
# Create a column showing population growth for each year
df_demog['pop_growth'] = df_demog['live_births'] - df_demog['deaths']
df_demog

## Delete Column

In [ ]:
df_demog.drop('pop_growth', axis=1, inplace=True)
df_demog

## Delete a Row

In [ ]:
df_demog.drop('1790', axis=0, inplace=True)
df_demog

## Manipulating Data

In [ ]:
# You can also search for phrases in the table

url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

response_gdp = requests.get(url, headers=headers)

df_gdp = pd.read_html(response_gdp.text)[2]
df_gdp


In [ ]:
# Delete a level of a multilevel column name
# La tabla se descargó sin multilevel column names originalmente, 
# pero se limpia así:
# df_gdp.columns = df_gdp.columns.droplevel()


In [ ]:
df_gdp = df_gdp.rename(columns={'Country/Territory':'country',
                                'IMF (2026)[1]':'imf_2026',
                                'World Bank (2025)[6]':'world_bank_2026',
                                'United Nations (2024)[7]':'un_2026'})
df_gdp

In [ ]:
# Keep only columns if they haven't used the same name prior
df_gdp = df_gdp.loc[:, ~df_gdp.columns.duplicated()]
df_gdp

In [ ]:
# Delete any rows with NaN values by taking only rows that don't contain NaNs
df_gdp = df_gdp[df_gdp['imf_2026'].notna()]
df_gdp


In [ ]:
# Remove []s and what is in them in Year column
# Removes brackets and what is inside for whole column
df_gdp['country'] = df_gdp['country'].str.replace(r"\[.*\]", "", regex=True).str.strip()
df_gdp

In [ ]:
# Rename country column


In [ ]:
# Remove * in Country column


In [ ]:
# Groupby allows you to group rows based on a column and perform a function
# Mean GDP by region


In [ ]:
# Median GDP by region


## More Ways of Messing with Data

In [ ]:
# Dictionary with ice cream sales data
dict1 = {'store':[1,2,1,2], 
         'flavor':['chocolate', 'vanilla', 'strawberry', 'chocolate'], 
         'sales': [26, 12, 18, 22]}

# Convert to Dataframe
ic_data = pd.DataFrame(dict1)
ic_data

In [ ]:
# Group data by the store number
by_store = ic_data.groupby('store')

In [ ]:
by_store.describe()

In [ ]:
# Get mean sales by store
by_store.mean()

In [ ]:
# Get sales total just for store 1
by_store.sum().loc[1]

In [ ]:
# You can use multiple functions of get a bunch


## Plotly

Plotly allows you to create over 40 beautiful interactive web-based visualizations that can be displayed in Jupyter notebooks or saved to HTML files. It is widely used to plot scientific, statistical and financial data.

You can install using Anaconda under the environment tab by searching for Plotly. You'll also need Cufflinks and a few other packages that you can install by running : conda install -c conda-forge cufflinks-py in your command line or terminal. Also you can use the commands pip install plotly and pip install cufflinks. Cufflinks connects Plotly to Pandas.

In [ ]:
import cufflinks as cf
import plotly.express as px
import plotly.graph_objects as go

# Make Plotly work in your Jupyter Notebook
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
# Use Plotly locally
cf.go_offline()

## Line Plot

In [ ]:
# Plot the value of a dollar invested over time
# Use included Google price data to make one plot
df_stocks = px.data.stocks()
px.line(df_stocks, x='date', y='GOOG', labels={'x':'Date',
                                              'y':'Value of Dollar'})
        

In [ ]:
# Multiple plots

px.line(df_stocks, x='date', y=['GOOG', 'AAPL'], labels={'x':'Date',
                                              'y':'Value of Dollar'},
        title='Apple vs Google')

# There are many line styles


In [ ]:
# There are many line styles


## Add Details to Plot

In [ ]:
aapl_df = pd.read_csv('AAPL.csv')
x = aapl_df['Date']
y = aapl_df['Adj Close']
aapl_df
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y))
fig.update_xaxes(rangeslider_visible=True,
                 title='Zoom on Dates Using Slider')
fig.update_yaxes(title='Stock Price (USD)')


## More Details

In [ ]:
msft_df = pd.read_csv('MSFT.csv')
x = msft_df['Date']
y = msft_df['Adj Close']
msft_df
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y))

# Add a range slider with buttons for dates
fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=10,
                     label="10D",
                     step="day",
                     stepmode="backward"),
                dict(count=1,
                     label="1M",
                     step="month",
                     stepmode="backward"),
                dict(count=6,
                     label="6M",
                     step="month",
                     stepmode="todate"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1Y",
                     step="year",
                     stepmode="backward"),
                dict(label="All", step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)
fig.update_yaxes(title="Stock Price (USD)")

## Candlestick Plots

In [ ]:
aapl_df

In [ ]:
# Candlestick charts are useful because they show the open and close in the
# wide part "Real Body" and the high and low using the Shadows or Wicks.
# They can be used to sense emotion in a stock in the near term.
x = aapl_df['Date']
close = aapl_df['Adj Close']
high = aapl_df['High']
low = aapl_df['Low']
openp = aapl_df['Open']

fig = go.Figure()

fig.add_trace(go.Candlestick(x=x, high=high, low=low, 
                             open=openp, close=close))



fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=10,
                     label="10D",
                     step="day",
                     stepmode="backward"),
                dict(count=1,
                     label="1M",
                     step="month",
                     stepmode="backward"),
                dict(count=6,
                     label="6M",
                     step="month",
                     stepmode="todate"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1Y",
                     step="year",
                     stepmode="backward"),
                dict(label="All", step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)
fig.update_layout(xaxis_title="Dates", yaxis_title="Stock Price (USD)", 
                  title="Apple Candlestick Chart")

# Add an annotation
fig.update_layout(annotations=[dict(x='2020-02-21', y=85, 
                                    text='Pandemic Effects Market',
                                   xanchor='right')])
# Add line defining an area
fig.update_layout(shapes=[dict(x0='2020-02-21', x1='2020-04-06', 
                                    y0=0, y1=1)])
# Add a rectangle
# fig.add_shape(type="rect",
#     x0='2020-02-21', y0=0, x1='2020-04-06', y1=145,
#     line=dict(
#         color="RoyalBlue",
#         width=2,
#     ),
#     fillcolor="LightSkyBlue",
# )

# Add a vertical rectangle with opacity
fig.add_vrect(
    x0='2020-02-21', x1='2020-04-06',
    fillcolor="LightSalmon", opacity=0.5,
    layer="below", line_width=0,
)

fig.show()

## Open-High-Low-Close (OHLC) Chart

In [ ]:
# While a candlestick chart has a rectangle representing the open and close
# An OHLC chart shows all 4 data points using ticks and when the opening
# and closing prices are fall apart that shows momentum up or down
# The tick on the left is the opening price and the left is the close
fig = go.Figure()

fig.add_trace(go.Ohlc(x=x, high=high, low=low, open=openp, close=close))

fig.show()

## Multiple Plots

In [ ]:
fig = go.Figure()

fig.add_trace(go.Ohlc(x=x, high=high, low=low, open=openp, close=close))

a_x = aapl_df['Date']
a_y = aapl_df['Adj Close']
fig.add_trace(go.Scatter(x=a_x, y=a_y,line=dict(color='blue', 
                                                width=1.5, dash="dot")))

fig.show()

## Scatter Plots

In [ ]:
x = np.arange(0,50,2)
y = np.arange(0,50,2)

# Create a figure to which I'll add plots
fig = go.Figure()

# Markers just shows the dots
fig.add_trace(go.Scatter(x=x, y=y, mode='markers'))

fig.show()

In [ ]:
# Use included Iris data set
df_iris = px.data.iris()
# Create a scatter plot by defining x, y, different color for count of provided
# column, size based on supplied column and additional data to display on hover
px.scatter(df_iris, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])

# Create a customized scatter with black marker edges with line width 2, opaque
# and colored based on width. Also show a scale on the right
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=df_iris.sepal_width, y=df_iris.sepal_length,
    mode='markers',
    marker_color=df_iris.sepal_width,
    text=df_iris.species,
    marker=dict(showscale=True)))
fig.update_traces(marker_line_width=2, marker_size=10)

# Working with a lot of data use Scattergl
fig = go.Figure(data=go.Scattergl(
    x = np.random.randn(100000),
    y = np.random.randn(100000),
    mode='markers',
    marker=dict(
        color=np.random.randn(100000),
        colorscale='Viridis',
        line_width=1)))
fig

## Histogram

In [ ]:
# Plot histogram based on rolling 2 dice
dice_1 = np.random.randint(1,7,5000)
dice_2 = np.random.randint(1,7,5000)
dice_sum = dice_1 + dice_2
# bins represent the number of bars to make
# Can define x label, color, title
# marginal creates another plot (violin, box, rug)
fig = px.histogram(dice_sum, nbins=11, labels={'value':'Dice Roll'},
             title='5000 Dice Roll Histogram', marginal='violin',
            color_discrete_sequence=['green'])

fig.update_layout(
    xaxis_title_text='Dice Roll',
    yaxis_title_text='Dice Sum',
    bargap=0.2, showlegend=False
)

In [ ]:
# Stack histograms based on different column data
df_tips = px.data.tips()
px.histogram(df_tips, x="total_bill", color="sex")